# Generated by Django 5.1.1 on 2024-11-28 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='budgetplanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('housing', models.IntegerField()),
                ('food', models.IntegerField()),
                ('shopping', models.IntegerField()),
                ('travelling', models.IntegerField()),
                ('entertainment', models.IntegerField()),
                ('health', models.IntegerField()),
                ('school', models.IntegerField()),
                ('busines', models.IntegerField()),
                ('socialservice', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='housing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='housing_expenses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
